/** @file Program.cs
 * 
 *  @author Automatically generated by Visual Studio 2008
 * 
 *  @brief entry point for the program
 */


using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows.Forms;

namespace BBB_GH_test
{
    /** A class which instantiates the program */
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [MTAThread]
        static void Main()
        {
            Application.Run(new Form1());
        }
    }
}